### ISSUE TITLE
Search using xStructure

### ISSUE THREAD

**Issue by ievgensalo** [syllant/idea-plugin-xstructure#10]
Hey!

I am using xStructure for custom XML. 

For example, I've added custom mapping using custom label 

``` xml
<mapping match="node" label="Name: {@name} - Value: {@value}"/>
```

 and I want to go to specific name in Structure tab.

Is it possible to navigate using xStructure by searching words in labels from xStructure?

**Comment by syllant** [comment]
Sorry, I'm not sure to understand what you mean by "navigate using xStructure by searching words in labels from xStructure". You mean a quick text search (Ctrl-F)?
